import React from 'react'
import Head from 'next/head'
import { TokenDapp } from '@/components/TokenDapp'
import styles from '../styles/project.module.css'
import { AlephiumConnectButton, useWallet } from '@alephium/web3-react'
import { tokenFaucetConfig } from '@/services/utils'
import Link from 'next/link'
import Navbar from '@/components/Navbar'

const Project: any = () => {
  const { connectionStatus } = useWallet()
  console.log('connectionStatus : ', connectionStatus)

  return (
    <div className={styles.main}>
      <video autoPlay muted loop className={styles.videoBackground}>
        <source src="/videos/bg.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      <div className="wrapper">
        <Navbar />
        <section className={styles.spotlight}>
          {connectionStatus === 'connected' && <TokenDapp config={tokenFaucetConfig} />}
          <AlephiumConnectButton.Custom>
            {({ isConnected, disconnect, show, account }) => {
              return isConnected ? (
                <button onClick={disconnect} className={styles.alBtnD}>
                  Disconnect
                </button>
              ) : (
                <button onClick={show} className={styles.alBtnC}>
                  Connect
                </button>
              )
            }}
          </AlephiumConnectButton.Custom>
          <Head>
            <title>Token Faucet</title>
            <meta name="description" content="Generated by @alephium/cli init" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </section>
        {/* <footer>
          <div>
            <h2>About Us</h2>
            <p>
              This is a decentralized app (DApp) built on the Alephium blockchain. Our mission is to provide secure,
              efficient, and user-friendly tools for managing and transacting tokens.
            </p>
          </div>
        </footer> */}
      </div>
    </div>
  )
}

export default Project
